### ISSUE TITLE
Long tag name overflows widget

### ISSUE THREAD

**Issue by wkhughes** [Fivium/jquery-tagger#20]
A long tag name will overflow the widget bounds when selected. A long tag does however work fine in the search suggestions.

**Comment by Palmr** [comment]
This can be "solved" by adding the following to your stylesheet:
```css
.tagger .tag {
  white-space: normal !important;
}
```

Note that this isn't on by default otherwise normal sized tags might end up displaying as larger blocks unexpectedly.

We might add an option for this in the future but I'll close this issue for now as it can easily be handled in userland css
